version: '3.8'

services:
  backend:
    build: 
      context: ./be
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - DB_HOST=boovkd434xr0zfz4t0mu-mysql.services.clever-cloud.com
      - DB_USER=ufiog8sb8qoqwfor
      - DB_PASSWORD=cVuFz7kXWKbG1LTkf7EK
      - DB_NAME=boovkd434xr0zfz4t0mu
    networks:
      - employee-app-network

  frontend:
    build: 
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - employee-app-network


networks:
  employee-app-network: