version: '3.8'

services:
  backend:
    build: 
      context: ./be
      dockerfile: Dockerfile
    ports:
      - "5003:5002"
    environment:
      - DATABASE_URL=mysql://root:OLHCqThmdmwZkrGfKyxHGXZlADWhJPSQ@autorack.proxy.rlwy.net:10971/railway
    networks:
      - employee-app-network

  frontend:
    build: 
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - employee-app-network

networks:
  employee-app-network:
    driver: bridge
